[env:m5stick-c-plus2]
platform = espressif32@6.4.0
board = m5stick-c
framework = arduino
board_build.filesystem = littlefs
lib_deps =
    m5stack/M5Unified@^0.2.13
    bblanchon/ArduinoJson@^7.0.0
monitor_speed = 115200
upload_speed = 1500000
